import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en-GB" className='h-full w-full bg-white'>
      <body className={`w-full h-full content-center${inter.className}`}>{children}</body>
    </html>
  )
}
