                    
export const appliedJobs = [
    {title: 'Senior Mobile Developer',
        location: 'Nairobi, Kenya',
        image: '/assets/eqty.png',
        applied: 'Applied 2 days ago',
},
    {title: 'Full Stack Software Developer',
        location: 'Mombasa, Kenya',
        image: '/assets/msft.png',
        applied: 'Applied 1 week ago',
},
    {title: 'React JS Software Developer',
        location: 'Eldoret, Kenya',
        image: '/assets/toptal.png',
        applied: 'Applied 2 weeks ago',
},
    {title: 'Next Js/TypeScript',
        location: 'Nairobi, Kenya',
        image: '/assets/cellulant.png',
        applied: 'Applied 2 days ago',
},
    {title: 'JavaScript Developer',
        location: 'Mombasa, Kenya',
        image: '/assets/im.png',
        applied: 'Applied 1 week ago',
},
    {title: 'React JS Software Developer',
    location: 'Eldoret, Kenya',
    image: '/assets/toptal.png',
    applied: 'Applied 2 weeks ago',
},
    {title: 'React JS Software Developer',
    location: 'Eldoret, Kenya',
    image: '/assets/toptal.png',
    applied: 'Applied 2 weeks ago',
},
    {title: 'Next Js/TypeScript',
    location: 'Nairobi, Kenya',
    image: '/assets/cellulant.png',
    applied: 'Applied 2 days ago',
},
    {title: 'JavaScript Developer',
    location: 'Mombasa, Kenya',
    image: '/assets/im.png',
    applied: 'Applied 1 week ago',
},
    {title: 'React JS Software Developer',
    location: 'Eldoret, Kenya',
    image: '/assets/toptal.png',
    applied: 'Applied 2 weeks ago',
},
]