export const draftJobs = [
    {title: 'Senior Mobile Developer',
        location: 'Nairobi, Kenya',
        image: '/assets/eqty.png',
        isApplied: 'Complete application',
},
    {title: 'Full Stack Software Developer',
        location: 'Mombasa, Kenya',
        image: '/assets/msft.png',
        isApplied: 'Complete application',
},
{title: 'React JS Software Developer',
        location: 'Eldoret, Kenya',
        image: '/assets/toptal.png',
        isApplied: 'Complete application',
},
]