export const topJobs = [
    {title:'Senior Mobile Developer',
        description:'Revolut is looking for mobile software developer to assist...',
        tags:['Android', 'Flutter'],
},
    {title:'Fullstack Software Developer',
        description:'Revolut is looking for fullstack software developer to handle...',
        tags:['Javascript', 'Python', 'React'],
},
    {title:'Senior Mobile Developer',
        description:'Revolut is looking for mobile software developer to assist...',
        tags:['Android', 'Flutter'],
},
    {title:'Senior Mobile Developer',
        description:'Revolut is looking for mobile software developer to assist...',
        tags:['Android', 'Flutter'],
},
    {title:'Senior Mobile Developer',
        description:'Revolut is looking for mobile software developer to assist...',
        tags:['Android', 'Flutter'],
},
    {title:'Senior Mobile Developer',
        description:'Revolut is looking for mobile software developer to assist...',
        tags:['Android', 'Flutter'],
},
]